- hosts: localhost
  become: yes

# tasks file for base-packages
  tasks:
    - name: Install a list of packages with a list variable
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - git
          - docker
  